!!python/object:nerfstudio.engine.trainer.TrainerConfig
_target: !!python/name:nerfstudio.engine.trainer.Trainer ''
data: null
experiment_name: sugar_streaming1
gradient_accumulation_steps:
  camera_opt: 100
  color: 10
  shs: 10
load_checkpoint: null
load_config: null
load_dir: null
load_scheduler: true
load_step: null
log_gradients: false
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  device_type: cuda
  dist_url: auto
  machine_rank: 0
  num_devices: 1
  num_machines: 1
  seed: 42
max_num_iterations: 15000
method_name: dn-splatter
mixed_precision: false
optimizers:
  camera_opt:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: &id001 !!python/name:torch.optim.adam.Adam ''
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: &id002 !!python/name:nerfstudio.engine.schedulers.ExponentialDecayScheduler ''
      lr_final: 5.0e-05
      lr_pre_warmup: 1.0e-08
      max_steps: 30000
      ramp: cosine
      warmup_steps: 0
  features_dc:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.0025
      max_norm: null
      weight_decay: 0
    scheduler: null
  features_rest:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.000125
      max_norm: null
      weight_decay: 0
    scheduler: null
  means:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.00016
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 1.6e-06
      lr_pre_warmup: 1.0e-08
      max_steps: 30000
      ramp: cosine
      warmup_steps: 0
  normals:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: null
  opacities:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.05
      max_norm: null
      weight_decay: 0
    scheduler: null
  quats:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: null
  scales:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.005
      max_norm: null
      weight_decay: 0
    scheduler: null
output_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- ltx
- projects
- Depth-Anything-3
- sugar_streaming1_output
pipeline: !!python/object:dn_splatter.dn_pipeline.DNSplatterPipelineConfig
  _target: !!python/name:dn_splatter.dn_pipeline.DNSplatterPipeline ''
  datamanager: !!python/object:dn_splatter.dn_datamanager.DNSplatterManagerConfig
    _target: !!python/name:dn_splatter.dn_datamanager.DNSplatterDataManager ''
    cache_compressed_images: false
    cache_images: gpu
    cache_images_type: float32
    camera_res_scale_factor: 1.0
    data: null
    dataloader_num_workers: 4
    dataparser: !!python/object:dn_splatter.data.normal_nerfstudio.NormalNerfstudioConfig
      _target: !!python/name:dn_splatter.data.normal_nerfstudio.NormalNerfstudio ''
      auto_scale_poses: true
      center_method: poses
      data: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - ltx
      - projects
      - Depth-Anything-3
      - sugar_streaming1_dataset
      depth_unit_scale_factor: 0.001
      downscale_factor: null
      eval_interval: 8
      eval_mode: fraction
      load_3D_points: false
      load_depth_confidence_masks: false
      load_depths: true
      load_normals: true
      load_pcd_normals: false
      mask_color: null
      normal_format: omnidata
      orientation_method: up
      scale_factor: 1.0
      scene_scale: 1.0
      train_split_fraction: 0.9
    eval_num_images_to_sample_from: -1
    eval_num_times_to_repeat_images: -1
    fps_reset_every: 100
    images_on_gpu: false
    masks_on_gpu: false
    max_thread_workers: null
    prefetch_factor: 4
    train_cameras_sampling_seed: 42
    train_cameras_sampling_strategy: random
  experiment_name: experiment
  model: !!python/object:dn_splatter.dn_model.DNSplatterModelConfig
    _target: !!python/name:dn_splatter.dn_model.DNSplatterModel ''
    background_color: random
    binary_opacities_threshold: 0.9
    camera_optimizer: !!python/object:nerfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:nerfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: 'off'
      optimizer: null
      rot_l2_penalty: 0.001
      scheduler: null
      trans_l2_penalty: 0.01
    collider_params:
      far_plane: 6.0
      near_plane: 2.0
    color_corrected_metrics: false
    cull_alpha_thresh: 0.005
    cull_scale_thresh: 0.5
    cull_screen_size: 0.15
    densify_grad_thresh: 0.0004
    densify_size_thresh: 0.01
    depth_lambda: 0.2
    depth_loss_type: !!python/object/apply:dn_splatter.losses.DepthLossType
    - EdgeAwareLogL1
    depth_tolerance: 0.1
    enable_collider: true
    eval_num_rays_per_chunk: 4096
    grid_shape: !!python/tuple
    - 16
    - 16
    - 8
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    max_gauss_ratio: 5.0
    max_gs_num: 2000000
    mcmc_opacity_reg: 0.01
    mcmc_scale_reg: 0.01
    n_split_samples: 2
    noise_lr: 500000.0
    normal_lambda: 0.05
    normal_supervision: mono
    num_downscales: 0
    num_random: 50000
    output_depth_during_training: true
    pearson_lambda: 0
    predict_normals: true
    prompt: null
    random_init: false
    random_scale: 10.0
    rasterize_mode: classic
    refine_every: 100
    regularization_strategy: dn-splatter
    reset_alpha_every: 30
    resolution_schedule: 3000
    sh_degree: 3
    sh_degree_interval: 1000
    smooth_loss_lambda: 0.1
    smooth_loss_type: !!python/object/apply:dn_splatter.losses.DepthLossType
    - TV
    sparse_lambda: 0.1
    sparse_loss_steps: 10
    split_screen_size: 0.05
    ssim_lambda: 0.2
    stop_screen_size_at: 4000
    stop_split_at: 12000
    strategy: default
    two_d_gaussians: true
    use_absgrad: true
    use_bilateral_grid: false
    use_binary_opacities: false
    use_depth_loss: true
    use_depth_smooth_loss: false
    use_normal_cosine_loss: false
    use_normal_loss: true
    use_normal_tv_loss: true
    use_scale_regularization: false
    use_sparse_loss: false
    warmup_length: 500
  num_pd_points: 1000000
  save_train_images: false
  skip_point_metrics: true
project_name: nerfstudio-project
prompt: null
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: false
start_paused: false
steps_per_eval_all_images: 1000000
steps_per_eval_batch: 500
steps_per_eval_image: 500
steps_per_save: 5000
timestamp: 2026-02-21_181031
use_grad_scaler: false
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  camera_frustum_scale: 0.1
  default_composite_depth: true
  image_format: jpeg
  jpeg_quality: 75
  make_share_url: false
  max_num_display_images: 512
  num_rays_per_chunk: 32768
  quit_on_train_completion: true
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: 7007
  websocket_port_default: 7007
vis: viewer+tensorboard
